name: Misk
favicon: null
layout_spectrum: 0.9353285536635667
typography_spectrum: 0.10431100311689079
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3006560888607055
  lightness: 0.6954592082183808
  saturation: 0.03854641201905906
  rhythmicContrast: 0.5029630789067596
purpose: []
